PROJECT_NAME  = "Mobven-Project"
PROJECT_BUNDLE = "com.mobven.Mobven-ProjectProd"
DEVELOPMENT_PROJECT_BUNDLE = "com.mobven.Mobven-Project"
PROJECT_SCHEME = "Mobven-Project"

# development build
lane :build_test do |values|
    #match(app_identifier: DEVELOPMENT_PROJECT_BUNDLE, type: "enterprise", readonly: true)
    build("DevelopmentRelease", "enterprise", "#{DEVELOPMENT_PROJECT_BUNDLE}"."match InHouse #{DEVELOPMENT_PROJECT_BUNDLE}")
end
    
# production build
lane :build_test do |values|
    #match(app_identifier: PROJECT_BUNDLE, type: "enterprise", readonly: true)
    build("ProductionRelease", "enterprise", "#{PROJECT_BUNDLE}"."match InHouse #{PROJECT_BUNDLE}")
end

def build(configuration, export_method, project_bundle, certificateName)
    gym( scheme: "#{PROJECT_SCHEME}",
    configuration: configuration,
    export_method: export_method,
    clean: true,
    export_options: {
            export_xcargs: "-allowProvisioningUpdates",
            provisioningProfiles: {
                project_bundle => certificateName,
            }
    }
    )
end
